language: node_js
sudo: required
node_js: 12
script:
- npm run test

cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=auburn-intelligent-academic-advisor-demo
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
before_deploy: npm install -g bx-blue-green
deploy:
- provider: script
  skip_cleanup: true
  script: bx-blue-green-travis
  on:
    branch: master
    repo: cls0076/auburn-intelligent-academic-advisor-demo
- provider: script
  skip_cleanup: true
  script: npx semantic-release